[tool.mypy]
strict = true
show_error_codes = true

[tool.black]
skip_string_normalization = true

[tool.ruff]
ignore = ["E501"]
line-length = 88
select = [
  "B",
  "C4",
  "COM",
  "E",
  "F",
  "FBT",
  "G",
  "I",
  "ICN",
  "N",
  "Q",
  "TID",
  "UP",
  "W",
]
target-version = "py38"

[tool.ruff.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"
multiline-quotes = "double"
